#!/usr/bin/env bash
# Installs, configures, and starts the web server
apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
mkdir -p /var/www/html /var/www/error
chmod -R 755 /var/www
echo 'Hello World!' > /var/www/html/index.html
echo -e "Ceci n\x27est pas une page" > /var/www/error/404.html
new_string="server_name _;\n\trewrite ^\/redirect_me google.com permanent;"
nstr1="\n\tadd_header X-Served-By \$hostname;"
nstr2="\n\terror_page 404 \/custom_404.html;\n\tlocation = \/custom_404.html {\n\t\troot \/usr\/share\/nginx\/html;\n\t\tinternal;\n\t}"
sed -i "s/server_name _;/$new_string$nstr1$nstr2/" /etc/nginx/sites-enabled/default
service nginx start
